# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
title = "ZacheryLiu's Blog"
weight = 2

[zh-cn]
languageName = "简体中文"
title = "ZacheryLiu 的个人博客"
weight = 1