# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Zachery-Liu"

[social.params]
icon = "github-fill"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/474705747"

[social.params]
icon = "icon_bilibili-circle"
